### ISSUE TITLE
Fix script not working if optional cli-arg "maxprice" not given

### ISSUE THREAD

**Issue by vpiskunov** [martynoconnor/shamrock-disco#2]
Considering the ‘maxprice’ arg is optional, the script doesn’t work(returns 400 error) when maxprice is not given. This is because the API url ends up having “None” in the last parameter. This is a fix for that, which will assign maxprice with an empty string when arg is not given (See Pull request #1 )

**Comment by martynoconnor** [comment]
Thanks for spotting that. I've merged all of your changes. Apologies it took me so long...
